pipeline {
  agent {
    label "saltmaster"
  }

  stages {
    stage('deploy plex and dependent services'){
      steps {
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh "kubectl apply -f plex/plex.yaml --wait=true"
      }
    }
  }
}