pipeline {
  agent {
    label "saltmaster"
  }

  stages {
    stage('deploy plex and dependent services'){
      steps {
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh "kubectl apply -f plex/badwolf/plex-namespace.yaml \
                          -f plex/badwolf/plex-pvc.yaml \
                          -f plex/badwolf/plex-service.yaml \
                          -f plex/badwolf/plex-mediaserver.yaml --wait=true"
      }
    }
  }
}