applications:
  ceph-mon:
    charm: ceph-mon
    channel: quincy/stable
    num_units: 3
    to:
      - 'lxd:2'
      - 'lxd:3'
      - 'lxd:4'
    options:
      monitor-count: 3
  ceph-osd:
    charm: ceph-osd
    channel: quincy/stable
    num_units: 6
    to:
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
    options:
      bluestore: 'True'
      bluestore-db: '/dev/nvme1n1'
      osd-devices: '/dev/sda /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/nvme2n1'
  ceph-fs:
    charm: ceph-fs
    channel: quincy/stable
    num_units: 3
    to:
      - 'lxd:2'
      - 'lxd:3'
      - 'lxd:4'
    options:
      pool-type: 'erasure-coded'
      ec-profile-device-class: hdd
      ec-profile-crush-locality: host
      ec-profile-k: 4
      ec-profile-m: 2
relations:
  - - ceph-osd:mon
    - ceph-mon:osd
  - - ceph-fs:ceph-mds
    - ceph-mon:mds
  - - ceph-mon:client
    - kubernetes-control-plane:ceph-client
  - - ceph-mon:admin
    - kubernetes-control-plane:ceph-storage
