applications:
  easyrsa:
    to:
      - '3'
  etcd:
    # in my homelab I don't have enough hosts to put these on dedicated hosts...   but it is not needed at this scale
    num_units: 3
    to:
      - '6'
      - '7'
      - '8'
  kubeapi-load-balancer:
    num_units: 1
    to:
      - '4'
  kubernetes-master:
    # this is not redundant as the charm defaults to
    # but only the first three hosts are bare metal, the rest are in a single kvm host...
    # so adding a second node would not add real redundancy
    num_units: 1
    options:
      # the following hurts platform security against compromised pods/containers, but is needed for rook to setup ceph
      allow-privileged: 'true'
    to:
      - '5'
  kubernetes-worker:
    num_units: 3
    options:
      ingress: 'true'
    to:
      - '0'
      - '1'
      - '2'
machines:
  '0':
    series: focal
  '1':
    series: focal
  '2':
    series: focal
  '3':
    series: focal
    constraints: arch=amd64 cpu-cores=1 mem=1G root-disk=8G
  '4':
    series: focal
    constraints: arch=amd64 cpu-cores=2 mem=4G root-disk=16G
  '5':
    series: focal
    constraints: arch=amd64 cpu-cores=2 mem=4G root-disk=64G
  '6':
    series: focal
    constraints: arch=amd64 cpu-cores=4 mem=8G root-disk=96G
  '7':
    series: focal
    constraints: arch=amd64 cpu-cores=4 mem=8G root-disk=96G
  '8':
    series: focal
    constraints: arch=amd64 cpu-cores=4 mem=8G root-disk=96G
