applications:
  easyrsa:
    to:
      - 'lxd:0'
  etcd:
    num_units: 3
    to:
      - 'lxd:1'
      - 'lxd:2'
      - 'lxd:3'
  kubeapi-load-balancer:
    num_units: 1
    expose: true
    to:
      - 'lxd:0'
  kubernetes-control-plane:
    num_units: 1
    to:
      - '0'
    options:
      # the following hurts platform security against compromised pods/containers, but is needed for rook to setup ceph
      # it is apparently needed for ceph-client and gpu usage, so it is staying until I switch off of juju.
      allow-privileged: 'true'
      enable-dashboard-addons: True
  kubernetes-worker:
    num_units: 8
    expose: true
    options:
      ingress: 'true'
    to:
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
machines:
  '0':
    series: jammy
  '1':
    series: jammy
  '2':
    series: jammy
  '3':
    series: jammy
  '4':
    series: jammy
  '5':
    series: jammy
  '6':
    series: jammy
  '7':
    series: jammy
  '8':
    series: jammy
