applications:
  containerd:
    options:
      channel: '1.24/edge'
  easyrsa:
    to:
      - 'lxd:0'
  etcd:
    num_units: 3
    to:
      - 'lxd:1'
      - 'lxd:2'
      - 'lxd:3'
  kubeapi-load-balancer:
    num_units: 1
    to:
      - 'lxd:4'
  kubernetes-control-plane:
    num_units: 1
#    options:
      # the following hurts platform security against compromised pods/containers, but is needed for rook to setup ceph
#      allow-privileged: 'true'
    to:
      - '0'
  kubernetes-worker:
    num_units: 4
    options:
      ingress: 'true'
    to:
      - '1'
      - '2'
      - '3'
      - '4'
  #    bluestore: 'True'
  #    bluestore-db: '/dev/nvme1n1'
  #    osd-devices: '/dev/sda /dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/nvme2n1'
machines:
  '0':
    series: jammy
  '1':
    series: jammy
  '2':
    series: jammy
  '3':
    series: jammy
  '4':
    series: jammy
