applications:
  easyrsa:
    to:
      - '0'
  etcd:
    num_units: 0
  kubeapi-load-balancer:
    num_units: 1
    to:
      - '1'
  kubernetes-control-plane:
    num_units: 0
    options:
      # the following hurts platform security against compromised pods/containers, but is needed for rook to setup ceph
      # it is apparently needed for ceph-client and gpu usage, so it is staying until I switch off of juju.
      allow-privileged: 'false'
      enable-dashboard-addons: True
  kubernetes-worker:
    num_units: 0
    expose: True
    options:
      ingress: False
machines:
  '0':
    series: jammy
  '1':
    series: jammy
