applications:
  easyrsa:
    to:
      - 'lxd:0'
  etcd:
    num_units: 3
    to:
      - 'lxd:1'
      - 'lxd:2'
      - 'lxd:3'
  kubeapi-load-balancer:
    num_units: 1
    to:
      - 'lxd:0'
  kubernetes-master:
    num_units: 1
    #options:
    #  # the following hurts platform security against compromised pods/containers, but is needed for rook to setup ceph
    #  allow-privileged: 'true'
    to:
      - '0'
  kubernetes-worker:
    num_units: 4
    options:
      ingress: 'true'
    to:
      - '1'
      - '2'
      - '3'
      - '4'
  ceph-mon:
    charm: cs:ceph-mon
    num_units: 3
    options:
      monitor-count: 3
      expected-osd-count: 3
      source: distro
    to:
      - 'lxd:1'
      - 'lxd:2'
      - 'lxd:3'
  ceph-osd:
    charm: cs:ceph-osd
    num_units: 3
    options:
      bluestore: 'True'
      bluestore-db: '/dev/nvme1n1'
      #ceph-public-network:
      #ceph-cluster-network:
      osd-devices: '/dev/sdb /dev/sdc /dev/sdd /dev/sde /dev/sdf /dev/nvme2n1'
      osd-encrypt: 'True'
      osd-recovery-max-active: 1
      prefer-ipv6: 'False'
      source: distro
    to:
      - '1'
      - '2'
      - '3'
machines:
  '0':
    series: focal
  '1':
    series: focal
  '2':
    series: focal
  '3':
    series: focal
  '4':
    series: focal
relations:
  - - ceph-osd:mon
    - ceph-mon:osd
  - - ceph-mon:admin
    - kubernetes-master
  - - ceph-mon:client
    - kubernetes-master
