pipeline {
  agent {
    label "kubectl"
  }

  stages {
    stage('bootstrap cluster if missing'){
      steps {
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh 'echo "TODO:  create conditional and run code below"'
        echo '''juju add-model kube HomeLab
             juju model-config -m kube default-series=focal
             juju add-machine -m kube wired-clam.khoyi.io
             juju add-machine -m kube fast-stag.khoyi.io
             juju add-machine -m kube hairy-hyena.khoyi.io'''
      }
    }
    stage('update juju deployment'){
      steps {
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh "cd k8s; juju deploy -m kube --map-machines=existing cs:bundle/charmed-kubernetes-519 --overlay changes.yaml; ./juju-block-io.sh"
        echo "I'll need to test if the kubernetes-master charm switches to active prematurely, but this should block IO until the deployment is complete."
      }
    }
    stage('post-deployment config'){
      steps {
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
        echo "TODO:  make this idempotent, remove rm command and use a force on the copy"
        sh "juju scp kubernetes-master/0:config ~/.kube/config"
        sh "rm -fv /home/ubuntu/.kube/config"
        sh "cp /root/.kube/config /home/ubuntu/.kube/"
        sh "chown ubuntu /home/ubuntu/.kube/config"
      }
    }
  }
}