


apiVersion: v1
kind: Namespace
metadata:
  name: folding-at-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-pvc-fah
  namespace: folding-at-home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-fs-replicated
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: folding-at-home
  namespace: folding-at-home
  labels:
    application: folding-at-home
spec:
  selector:
    matchLabels:
      application: folding-at-home
  template:
    metadata:
      labels:
        application: folding-at-home
    spec:
      containers:
        - name: fahclient
          image: foldingathome/fah-gpu:latest
          env:
            - name: USER
              value: "devops-brain"
            - name: POWER
              value: "light"
            - name: TEAM
              value: "234679"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: fahclient
              mountPath: /fah
              subPathExpr: $(NODE_NAME)
          ports:
            - containerPort: 7396
          #readinessProbe:
          #  httpGet:
          #    path: /favicon.ico
          #    port: 7396
          resources:
            limits:
              cpu: 6
              memory: 4Gi
            requests:
              memory: 200Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: fahclient
          persistentVolumeClaim:
            claimName: csi-cephfs-pvc-fah
            readOnly: false

