pipeline {
  agent {
    label "saltmaster"
  }

  stages {
    stage('deploy folding at home daemonset and pvc'){
      steps {
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh "kubectl apply -f fahclient/folding.yaml --wait=true"
      }
    }
  }
}