pipeline {
  agent {
    label "kubectl"
  }

  stages {
    stage('deploy postgres cluster for nextcloud'){
      steps {
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh "#helm upgrade -i --create-namespace --namespace nextcloud nextcloudsql ./common/SGCluster/ \
            #--set cluster_name=nextcloudsql \
            #--atomic --timeout 300s "
      }
    }
    stage('deploy nextcloud'){
      steps {
        echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
        sh "helm repo add nextcloud https://nextcloud.github.io/helm/"
        sh "helm repo update"
        sh """helm upgrade -i --create-namespace --namespace nextcloud nextcloud nextcloud/nextcloud \
            --version 3.5.4 \
            --set ingress.className=nginx \
            --set ingress.enabled=true \
            --set image.flavor=fpm \
            --set nextcloud.host=nextcloud.khoyi.io \
            --set nextcloud.username=brian \
            --set internalDatabase.enabled=false \
            --set externalDatabase.enabled=true \
            --set externalDatabase.type=postgresql \
            --set externalDatabase.host="zotac-mini-01.khoyi.io:5432"  \
            --set externalDatabase.database=nextcloud \
            --set externalDatabase.user=nextcloud \
            --set externalDatabase.password=gDK1q0JvNq0sOWl0 \
            --set redis.enabled=false \
            --set cronjob.enabled=false \
            --set cronjob.schedule="*/15 * * * *" \
            --set service.type=ClusterIP \
            --set persistence.enabled=true \
            --set persistance.size=1024Ti \
            --set persistance.nextcloudData.storageClass=cephfs \
            --set persistance.nextcloudData.size=1024Ti \
            --set rbac.enabled=true \
            --set hpa.enabled=true \
            --set hpa.minPods=1 \
            --set hpa.maxPods=12 \
            --set metrics.enabled=true"""
      }
    }
  }
}