applications:
  containerd:
    charm: 'cs:~containers/containerd-80'
    series: bionic
    annotations:
      gui-x: '475'
      gui-y: '800'
  easyrsa:
    charm: 'cs:~containers/easyrsa-318'
    num_units: 1
    series: bionic
    annotations:
      gui-x: '90'
      gui-y: '420'
    to:
      - '9'
  etcd:
    charm: 'cs:~containers/etcd-521'
    num_units: 3
    options:
      channel: 3.3/stable
    series: bionic
    annotations:
      gui-x: '800'
      gui-y: '420'
    to:
      - '6'
      - '7'
      - '8'
  flannel:
    charm: 'cs:~containers/flannel-492'
    series: bionic
    annotations:
      gui-x: '475'
      gui-y: '605'
  kubeapi-load-balancer:
    charm: 'cs:~containers/kubeapi-load-balancer-730'
    num_units: 1
    expose: true
    series: bionic
    annotations:
      gui-x: '450'
      gui-y: '250'
    to:
      - '4'
  kubernetes-master:
    charm: 'cs:~containers/kubernetes-master-850'
    num_units: 1
    series: bionic
    annotations:
      gui-x: '800'
      gui-y: '850'
    to:
      - '5'
  kubernetes-worker:
    charm: 'cs:~containers/kubernetes-worker-682'
    num_units: 4
    options:
      labels: FatTwin
    expose: true
    series: bionic
    annotations:
      gui-x: '90'
      gui-y: '850'
    to:
      - '0'
      - '1'
      - '2'
      - '3'
  ceph-osd:
    charm: 'cs:ceph-osd-303'
    num_units: 4
    options:
      bluestore: false
      osd-devices: /dev/sdc /dev/sdd /dev/sde /dev/sdf
      osd-encrypt: true
      osd-journal: /dev/sdb
    series: bionic
    annotations:
      gui-x: '90'
      gui-y: '1100'
    to:
      - '0'
      - '1'
      - '2'
      - '3'
  ceph-mon:
    charm: 'cs:ceph-mon-48'
    num_units: 3
    options:
      expected-osd-count: 8
      pgs-per-osd: 200
    series: bionic
    annotations:
      gui-x: '800'
      gui-y: '1100'
    to:
      - '0'
      - '1'
      - '2'
relations:
  - - 'kubernetes-master:kube-api-endpoint'
    - 'kubeapi-load-balancer:apiserver'
  - - 'kubernetes-master:loadbalancer'
    - 'kubeapi-load-balancer:loadbalancer'
  - - 'kubernetes-master:kube-control'
    - 'kubernetes-worker:kube-control'
  - - 'kubernetes-master:certificates'
    - 'easyrsa:client'
  - - 'etcd:certificates'
    - 'easyrsa:client'
  - - 'kubernetes-master:etcd'
    - 'etcd:db'
  - - 'kubernetes-worker:certificates'
    - 'easyrsa:client'
  - - 'kubernetes-worker:kube-api-endpoint'
    - 'kubeapi-load-balancer:website'
  - - 'kubeapi-load-balancer:certificates'
    - 'easyrsa:client'
  - - 'flannel:etcd'
    - 'etcd:db'
  - - 'flannel:cni'
    - 'kubernetes-master:cni'
  - - 'flannel:cni'
    - 'kubernetes-worker:cni'
  - - 'containerd:containerd'
    - 'kubernetes-worker:container-runtime'
  - - 'containerd:containerd'
    - 'kubernetes-master:container-runtime'
  - - 'ceph-osd:mon'
    - 'ceph-mon:osd'
  - - 'ceph-mon:client'
    - 'kubernetes-master:ceph-client'
  - - 'ceph-mon:admin'
    - 'kubernetes-master:ceph-storage'
  - - 'ceph-mon:prometheus'
    - 'kubernetes-worker:kube-api-endpoint'
  - - 'ceph-mon:prometheus'
    - 'kubeapi-load-balancer:apiserver'
machines:
  '0':
    series: bionic
  '1':
    series: bionic
  '2':
    series: bionic
  '3':
    series: bionic
  '4':
    series: bionic
    constraints: arch=amd64 cpu-cores=2 mem=2G root-disk=8G
  '5':
    series: bionic
    constraints: arch=amd64 cpu-cores=2 mem=4G root-disk=64G
  '6':
    series: bionic
    constraints: arch=amd64 cpu-cores=4 mem=8G root-disk=8G
  '7':
    series: bionic
    constraints: arch=amd64 cpu-cores=4 mem=8G root-disk=8G
  '8':
    series: bionic
    constraints: arch=amd64 cpu-cores=4 mem=8G root-disk=8G
  '9':
    series: bionic
    constraints: arch=amd64 cpu-cores=1 mem=1G root-disk=8G
