applications:
  easyrsa:
    to:
      - '3'
  etcd:
    num_units: 3
    to:
      - '0'
      - '1'
      - '2'
  kubeapi-load-balancer:
    num_units: 1
    to:
      - '4'
  kubernetes-master:
    num_units: 1
    to:
      - '5'
  kubernetes-worker:
    num_units: 3
    to:
      - '0'
      - '1'
      - '2'
machines:
  '0':
    series: focal
  '1':
    series: focal
  '2':
    series: focal
  '3':
    series: focal
    constraints: arch=amd64 cpu-cores=1 mem=1G root-disk=8G
  '4':
    series: focal
    constraints: arch=amd64 cpu-cores=2 mem=4G root-disk=16G
  '5':
    series: focal
    constraints: arch=amd64 cpu-cores=2 mem=4G root-disk=64G
