
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexvc
  namespace: plex
  labels:
    app: plex
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexmedia_symlinks
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Koi-Pond
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Rose-Garden
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Dragons-Den
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Donna-Collection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Roger-Roger
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: rook-cephfs
