

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-jnlp
  namespace: plex
  labels:
    app: plex-jnlp
spec:
  selector:
    matchLabels:
      app: plex-jnlp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex-jnlp
    spec:
      containers:
        - image: khoyi/jnlp-slave:latest
          name: jnlp
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: jenkins_master
              value: "http://192.168.77.0:8080"
          command: ["jenkins-slave", "-url", "http://192.168.77.0:8080", "-workDir=/home/jenkins/agent", "f8785d178afa3882b7eb243e40d4a3a679209925d47bb5c65afba81fe49db0de", "k8splex"]
          resources:
            limits:
              cpu: "2000m"
              memory: 8Gi
            requests:
              cpu: "2000m"
              memory: 8Gi
          volumeMounts:
            - name: plexbackups
              mountPath: /srv/backups
            - name: plexmedia-symlinks
              mountPath: /media
            - name: dvr
              mountPath: /srv/masters_DVR
            - name: koi-pond
              mountPath: /srv/masters_koi-pond
            - name: rose-garden
              mountPath: /srv/masters_rose-garden
            - name: dragons-den
              mountPath: /srv/masters_dragons-den
            - name: donna-collection
              mountPath: /srv/masters_donna-collection
      securityContext:
        fsGroup: 1000
      volumes:
        - name: plexbackups
          persistentVolumeClaim:
            claimName: plexbackups
            readOnly: false
        - name: plexmedia-symlinks
          persistentVolumeClaim:
            claimName: plexmedia-symlinks
            readOnly: false
        - name: dvr
          persistentVolumeClaim:
            claimName: dvr
            readOnly: false
        - name: koi-pond
          persistentVolumeClaim:
            claimName: koi-pond
            readOnly: false
        - name: rose-garden
          persistentVolumeClaim:
            claimName: rose-garden
            readOnly: false
        - name: dragons-den
          persistentVolumeClaim:
            claimName: dragons-den
            readOnly: false
        - name: donna-collection
          persistentVolumeClaim:
            claimName: donna-collection
            readOnly: false

