

apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
    tier: frontend
spec:
  selector:
    matchLabels:
      app: plex
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
        tier: frontend
    spec:
      containers:
        - image: plexinc/pms-docker:plexpass
          name: plex
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 32400
              name: plex
          volumeMounts:
            - name: plexconfig
              mountPath: /config
      volumes:
        - name: plexconfig
          persistentVolumeClaim:
            claimName: plexconfig
