
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexvc
  namespace: plex
  labels:
    app: plex
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
