
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexconfig
  namespace: plex
  labels:
    app: plex
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexmedia-symlinks
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koi-pond
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: rook-cephfs
