
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexconfig
  namespace: plex
  labels:
    app: plex
spec:
  storageClassName: ceph-ext4
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexmedia-symlinks
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexbackups
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koi-pond
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Ti
  storageClassName: cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvr
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Ti
  storageClassName: cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rose-garden
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Ti
  storageClassName: cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dragons-den
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Ti
  storageClassName: cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: donna-collection
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Ti
  storageClassName: cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roger-roger
  namespace: plex
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Ti
  storageClassName: cephfs
