apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name:  {{ .Values.cluster_name }}
spec:
  instances: {{ .Values.instance_count }}
  postgres:
    version: "{{ .Values.postgres.version }}"
    extensions:
      - name: 'hstore'
  pods:
    persistentVolume:
      size: "{{ .Values.storage.size }}"
      storageClass: "{{ .Values.storage.class }}"
  sgInstanceProfile: "{{ .Values.sgInstanceProfile }}"